-- ==========================================================
-- LASPOERJ - CONFIGURAÇÕES EDITÁVEIS DO SITE
-- ==========================================================

create table if not exists public.configuracoes_site (
  id bigint generated by default as identity primary key,
  chave text not null unique,
  valor text,
  descricao text,
  updated_at timestamptz default now()
);

alter table public.configuracoes_site enable row level security;

grant select on table public.configuracoes_site to anon, authenticated;
grant insert, update, delete on table public.configuracoes_site to authenticated;

drop policy if exists "Publico pode ler configuracoes"
on public.configuracoes_site;

create policy "Publico pode ler configuracoes"
on public.configuracoes_site
for select
to anon, authenticated
using (true);

drop policy if exists "Administradores podem criar configuracoes"
on public.configuracoes_site;

create policy "Administradores podem criar configuracoes"
on public.configuracoes_site
for insert
to authenticated
with check (
  (select public.tem_acesso_admin())
);

drop policy if exists "Administradores podem editar configuracoes"
on public.configuracoes_site;

create policy "Administradores podem editar configuracoes"
on public.configuracoes_site
for update
to authenticated
using (
  (select public.tem_acesso_admin())
)
with check (
  (select public.tem_acesso_admin())
);

drop policy if exists "Administradores podem excluir configuracoes"
on public.configuracoes_site;

create policy "Administradores podem excluir configuracoes"
on public.configuracoes_site
for delete
to authenticated
using (
  (select public.tem_acesso_admin())
);

-- Configurações iniciais
insert into public.configuracoes_site (chave, valor, descricao)
values
  (
    'sobre_titulo',
    'Sobre a LASPOERJ',
    'Título principal da seção Sobre'
  ),
  (
    'sobre_texto_1',
    'A LASPOERJ — Liga Acadêmica de Saúde Pública Odontológica da Estácio RJ — nasce com o compromisso de aproximar a formação acadêmica da realidade social da população.',
    'Primeiro parágrafo da seção Sobre'
  ),
  (
    'sobre_texto_2',
    'Nosso propósito é fortalecer o olhar crítico, científico e humano dos estudantes de Odontologia, valorizando os princípios do SUS, a atenção primária, a integralidade do cuidado e a promoção da saúde bucal coletiva.',
    'Segundo parágrafo da seção Sobre'
  ),
  (
    'sobre_texto_3',
    'Por meio de ações de ensino, pesquisa e extensão, buscamos construir uma odontologia mais acessível, preventiva, territorializada e comprometida com a transformação social.',
    'Terceiro parágrafo da seção Sobre'
  ),
  (
    'compromisso_titulo',
    'Nosso compromisso',
    'Título do card de compromisso'
  ),
  (
    'compromisso_texto',
    'Formar estudantes conscientes do papel social da Odontologia e preparados para atuar junto à comunidade.',
    'Texto do card de compromisso'
  ),
  (
    'instagram',
    '@laspoerj',
    'Instagram exibido no site'
  ),
  (
    'email_contato',
    'ligacademicasp@gmail.com',
    'E-mail público de contato'
  ),
  (
    'endereco',
    'Avenida Alfredo Balthazar da Silveira, nº 580 - Recreio dos Bandeirantes, Rio de Janeiro - RJ, 22790-710',
    'Endereço público da LASPOERJ'
  )
on conflict (chave) do nothing;
