-- ==========================================================
-- LASPOERJ - EQUIPE EDITÁVEL
-- Diretoria + Professores Orientadores
-- ==========================================================

create table if not exists public.equipe (
  id bigint generated by default as identity primary key,
  nome text not null,
  cargo text not null,
  bio text,
  foto_url text,
  grupo text not null default 'diretoria',
  ordem integer not null default 0,
  ativo boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),

  constraint equipe_grupo_check
    check (grupo in ('diretoria', 'orientador'))
);

alter table public.equipe enable row level security;

grant select on table public.equipe to anon, authenticated;
grant insert, update, delete on table public.equipe to authenticated;

drop policy if exists "Publico pode ver equipe ativa"
on public.equipe;

create policy "Publico pode ver equipe ativa"
on public.equipe
for select
to anon, authenticated
using (ativo = true);

drop policy if exists "Administradores podem ver toda equipe"
on public.equipe;

create policy "Administradores podem ver toda equipe"
on public.equipe
for select
to authenticated
using ((select public.tem_acesso_admin()));

drop policy if exists "Administradores podem criar equipe"
on public.equipe;

create policy "Administradores podem criar equipe"
on public.equipe
for insert
to authenticated
with check ((select public.tem_acesso_admin()));

drop policy if exists "Administradores podem editar equipe"
on public.equipe;

create policy "Administradores podem editar equipe"
on public.equipe
for update
to authenticated
using ((select public.tem_acesso_admin()))
with check ((select public.tem_acesso_admin()));

drop policy if exists "Administradores podem excluir equipe"
on public.equipe;

create policy "Administradores podem excluir equipe"
on public.equipe
for delete
to authenticated
using ((select public.tem_acesso_admin()));

-- Dados iniciais atuais do site.
-- O WHERE NOT EXISTS evita duplicar caso o SQL seja executado novamente.

insert into public.equipe
  (nome, cargo, bio, foto_url, grupo, ordem, ativo)
select *
from (
  values
    (
      'Iasmim Lorena',
      'Presidente',
      'Idealizadora da LASPOERJ, estudante de Odontologia e apaixonada por saúde coletiva, SUS, endodontia e transformação social.',
      '/diretoria/iasmim.jpg',
      'diretoria',
      1,
      true
    ),
    (
      'Riquelme Ferreira',
      'Vice-presidente',
      'Atua no apoio à organização institucional, projetos e fortalecimento das ações acadêmicas e extensionistas da Liga.',
      '/diretoria/riquelme.jpg',
      'diretoria',
      2,
      true
    ),
    (
      'Patrick Klen',
      'Secretário-Geral',
      'Responsável pelo suporte administrativo, registros, atas e comunicação interna da LASPOERJ.',
      '/diretoria/patrick.jpg',
      'diretoria',
      3,
      true
    ),
    (
      'Marcos Vinícius',
      'Diretor de Fotografia e Comunicação',
      'Atua na identidade visual, fotografia, divulgação e comunicação digital da Liga.',
      '/diretoria/marcos.jpg',
      'diretoria',
      4,
      true
    ),
    (
      'Isabella Veloso',
      'Diretora de Pesquisa',
      'Atua no desenvolvimento científico da Liga, organização de estudos, pesquisas e produções acadêmicas.',
      '/diretoria/isabella.jpg',
      'diretoria',
      5,
      true
    ),
    (
      'Prof. Rodrigo Arkader',
      'Diretor Científico',
      'Professor orientador da LASPOERJ, contribuindo para o desenvolvimento científico, acadêmico e institucional da Liga.',
      '/orientadores/arkader.jpg',
      'orientador',
      1,
      true
    ),
    (
      'Profª Luciane Monte Alto',
      'Diretora Científica',
      'Professora orientadora da LASPOERJ, com atuação voltada à extensão, cuidado humanizado e integração entre universidade e comunidade.',
      '/orientadores/luciane.jpg',
      'orientador',
      2,
      true
    )
) as novo(nome, cargo, bio, foto_url, grupo, ordem, ativo)
where not exists (
  select 1
  from public.equipe
);
