-- ==========================================================
-- LASPOERJ — DOCUMENTOS PÚBLICOS + STORAGE
-- Execute UMA VEZ no Supabase > SQL Editor.
-- ==========================================================

create table if not exists public.documentos_publicos (
  id bigint generated by default as identity primary key,
  titulo text not null,
  descricao text,
  categoria text not null default 'Outro',
  arquivo_url text not null,
  ordem integer not null default 1,
  publicado boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.documentos_publicos enable row level security;

grant select on table public.documentos_publicos to anon, authenticated;
grant insert, update, delete on table public.documentos_publicos to authenticated;

drop policy if exists "Publico pode ler documentos publicados"
on public.documentos_publicos;

create policy "Publico pode ler documentos publicados"
on public.documentos_publicos
for select
to anon, authenticated
using (publicado = true);

drop policy if exists "Administradores podem ler todos documentos"
on public.documentos_publicos;

create policy "Administradores podem ler todos documentos"
on public.documentos_publicos
for select
to authenticated
using ((select public.tem_acesso_admin()));

drop policy if exists "Administradores podem criar documentos"
on public.documentos_publicos;

create policy "Administradores podem criar documentos"
on public.documentos_publicos
for insert
to authenticated
with check ((select public.tem_acesso_admin()));

drop policy if exists "Administradores podem editar documentos"
on public.documentos_publicos;

create policy "Administradores podem editar documentos"
on public.documentos_publicos
for update
to authenticated
using ((select public.tem_acesso_admin()))
with check ((select public.tem_acesso_admin()));

drop policy if exists "Administradores podem excluir documentos"
on public.documentos_publicos;

create policy "Administradores podem excluir documentos"
on public.documentos_publicos
for delete
to authenticated
using ((select public.tem_acesso_admin()));

-- ==========================================================
-- BUCKET PÚBLICO DE PDFs
-- ==========================================================

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'documentos-publicos',
  'documentos-publicos',
  true,
  10485760,
  array['application/pdf']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Publico pode ler PDFs institucionais"
on storage.objects;

create policy "Publico pode ler PDFs institucionais"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'documentos-publicos');

drop policy if exists "Administradores podem enviar PDFs institucionais"
on storage.objects;

create policy "Administradores podem enviar PDFs institucionais"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'documentos-publicos'
  and (select public.tem_acesso_admin())
);

drop policy if exists "Administradores podem atualizar PDFs institucionais"
on storage.objects;

create policy "Administradores podem atualizar PDFs institucionais"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'documentos-publicos'
  and (select public.tem_acesso_admin())
)
with check (
  bucket_id = 'documentos-publicos'
  and (select public.tem_acesso_admin())
);

drop policy if exists "Administradores podem excluir PDFs institucionais"
on storage.objects;

create policy "Administradores podem excluir PDFs institucionais"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'documentos-publicos'
  and (select public.tem_acesso_admin())
);
